server:
  port: ${HOST_PORT:8080}
spring:
  application:
    name: "ms-notification"
  mail:
    host: smtp.gmail.com
    port: 587
    username: notificationms12@gmail.com
    password: mpgh lgtw bjef voue
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:notificationdb}
    username: ${DB_USER:postgrest}
    password: ${DB_PASSWORD:post1234}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
  h2:
    console:
      enabled: true
      path: /h2-console
  webflux:
    base-path: /api

app:
  async:
    app:
      brokerType: rabbitmq
      createTopology: true
      domain:
        events:
          exchange: events.topic
          eventsSuffix: subsEvents
          notificationSuffix: notification
      direct:
        exchange: directMessages
      connectionProperties:
        host: ${RABBIT_HOST:localhost}
        port: ${RABBIT_PORT:5672}
        username: ${RABBIT_USER:ms-notification}
        password: ${RABBIT_PASS:noti123}
        virtualHost: ${RABBIT_VHOST:micro}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui